version: '3'
services:
  nginx:
    build:
      context: docker/nginx
    container_name: inventory_app_nginx
    volumes:
      - .:/var/www/app
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - inventory_app_network
    ports:
      - "${HTTP_EXPO_PORT}:80"

  php-fpm:
    build:
      context: docker/php-fpm
    container_name: inventory_app_php-fpm
    working_dir: /var/www/app
    volumes:
      - .:/var/www/app
      - ./docker/php-fpm/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - inventory_app_network
    environment:
      PHP_IDE_CONFIG: ${PHP_IDE_CONFIG}

  db:
    image: postgres:15
    container_name: inventory_app_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./docker/postgresql_data:/var/lib/postgresql/data
    networks:
      - inventory_app_network
    ports:
      - "${DB_EXPO_PORT}:5432"

networks:
  inventory_app_network:
    driver: bridge
