version: '3'
services:
  nginx:
    build:
      context: docker/nginx
    container_name: inventory_app_nginx
    volumes:
      - .:/var/www/app
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - inventory_app_network

  php-fpm:
    build:
      context: docker/php-fpm
    container_name: inventory_app_php-fpm
    working_dir: /var/www/app
    volumes:
      - .:/var/www/app
      - ./docker/php-fpm/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - inventory_app_network

  db:
    image: postgres:15
    container_name: inventory_app_db
    volumes:
      - ./docker/postgresql_data:/var/lib/postgresql/data
    networks:
      - inventory_app_network

networks:
  inventory_app_network:
    driver: bridge
