name: Deploy
on:
  pull_request:
    branches: [ "master" ]
    types:
      - closed
permissions:
  contents: read
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    # only if PR was merged
    if: github.event.pull_request.merged == true
    environment: production
    steps:
      - name: Configure SSH
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.PRIVATE_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H ${{ vars.SERVER_NAME }} > ~/.ssh/known_hosts
      - name: Cloning the project
        run: ssh ${{ secrets.DEPLOY_USER }}@${{ vars.SERVER_NAME }} "sudo rm -rf ${{secrets.WORKING_DIR }} &&
          mkdir ${{secrets.WORKING_DIR }} &&
          cd ${{secrets.WORKING_DIR }} &&
          git clone git@github.com:amarkhai/inventory_it.git . &&
          sudo chown www-data:www-data ${{secrets.WORKING_DIR }} -R &&
          sh deploy.sh ${{ vars.SERVER_NAME }} ${{secrets.DB_DRIVER }} ${{secrets.DB_USER }} ${{secrets.DB_PASSWORD }} ${{secrets.DB_NAME }} ${{secrets.DB_HOST }} ${{secrets.DB_PORT }} ${{secrets.DB_DSN }} ${{secrets.JWT_TOKEN_EXPIRATION_TIME }} ${{secrets.JWT_SECRET }}"
      - name: cleanup
        run: rm -rf ~/.ssh



